#!/bin/bash

for file in $( ls |sort ) ; do
if [ -d $file ]
then
echo "$file is a directory"
fi

if [ -f $file ]
then 
	echo "$file is a ordinary file"
fi

done
number=10
while [ $number -gt 0 ] ; do
	echo $number
	 sleep 19               
	 number=$[ $number - 1 ]
done
